import React, { useEffect, useMemo, useState } from "react";
import type { Product, Role, User, VideoProject } from "./types";
import * as service from "./api";
import "./migrated.css";

type Page = "studio" | "library" | "rank" | "favorites" | "teacher" | "dashboard" | "store" | "video" | "profile" | "admin";
const menus: Array<{ id: Page; label: string; icon: string; roles: Role[] }> = [
  { id: "studio", label: "智能选品", icon: "⌂", roles: ["admin", "teacher", "student"] },
  { id: "library", label: "选品库", icon: "▣", roles: ["admin", "student"] },
  { id: "rank", label: "新品榜单", icon: "♜", roles: ["admin", "teacher", "student"] },
  { id: "favorites", label: "采集箱", icon: "☆", roles: ["admin", "student"] },
  { id: "teacher", label: "教师看板", icon: "▤", roles: ["admin", "teacher"] },
  { id: "dashboard", label: "数据看板", icon: "◔", roles: ["admin", "teacher"] },
  { id: "store", label: "店铺管理", icon: "▥", roles: ["admin", "teacher", "student"] },
  { id: "video", label: "视频生成", icon: "▶", roles: ["admin", "teacher", "student"] },
  { id: "profile", label: "个人中心", icon: "⚙", roles: ["admin", "teacher", "student"] },
  { id: "admin", label: "系统管理", icon: "▦", roles: ["admin"] },
];
function title(p: Product) { return p.title || p.derived_title || "未命名商品"; }
function picture(p: Product) { return p.image_url || p.supplier_image_url || ""; }
function money(p: Product) { const n = Number(p.price ?? p.supplier_price ?? 0); return `${p.currency === "CNY" || p.region === "CN" ? "¥" : p.region === "JP" ? "円" : "$"}${n.toFixed(2)}`; }
function pid(p: Product) { return p.id ?? p.source_product_id ?? title(p); }

function Login({ done }: { done: (u: User) => void }) { const [account, setAccount] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); return <div className="login-page"><div className="login-visual"><div className="brand-mark large">TK</div><h1>益行跨境 AI 平台</h1><p>TikTok 日本市场智能选品工作台</p></div><form className="login-card" onSubmit={async (e) => { e.preventDefault(); setError(""); try { done(await service.login(account, password)); } catch (x) { setError(x instanceof Error ? x.message : "登录失败"); } }}><h2>欢迎回来</h2><label>账号<input value={account} onChange={(e) => setAccount(e.target.value)} required /></label><label>密码<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} required /></label>{error && <div className="error">{error}</div>}<button className="primary">登录</button></form></div>; }

function Products({ page, rows, onSelect, selected, onCollect }: { page: Page; rows: Product[]; onSelect: (p: Product) => void; selected: Product | null; onCollect: (p: Product) => void }) { return <div className="workspace"><section className="products"><div className="section-heading"><div><h2>{page === "library" ? "选品库" : page === "favorites" ? "采集箱" : "新品榜单"}</h2><p>{rows.length} 个商品</p></div></div><div className="product-grid">{rows.map((p) => <article className={selected && pid(selected) === pid(p) ? "product selected" : "product"} key={String(pid(p))} onClick={() => onSelect(p)}><div className="image-wrap">{picture(p) ? <img src={picture(p)} loading="lazy" /> : <div className="image-empty">暂无图片</div>}</div><h3>{title(p)}</h3><div className="product-tag">{p.source_type || p.category || "商品"}</div><div className="product-meta"><strong>{money(p)}</strong><span>销量 {Number(p.sales_count ?? p.supplier_sales_count ?? 0).toLocaleString()}</span></div><button onClick={(e) => { e.stopPropagation(); onCollect(p); }}>加入采集箱</button></article>)}</div>{!rows.length && <div className="empty-state">暂无数据</div>}</section><aside className="report"><h2>选品分析报告</h2>{selected ? <><div className="report-product">{picture(selected) ? <img src={picture(selected)} /> : <div className="image-empty">暂无图片</div>}<div><h3>{title(selected)}</h3><strong>{money(selected)}</strong><p>请从详情页查看完整分析</p></div></div><button className="primary full" onClick={() => onCollect(selected)}>加入采集箱</button></> : <div className="empty-state">请选择商品</div>}</aside></div>; }

function Teacher({ notice }: { notice: (s: string) => void }) { const [sources, setSources] = useState<Product[]>([]); const [source, setSource] = useState<Product | null>(null); const [derived, setDerived] = useState<Product[]>([]); useEffect(() => { service.getTeacherProducts().then((list) => { setSources(list); setSource(list[0] || null); }).catch((e) => notice(e instanceof Error ? e.message : "读取教师看板失败")); }, []); useEffect(() => { if (source) service.getTeacherDerived(pid(source)).then(setDerived).catch((e) => notice(e instanceof Error ? e.message : "读取衍生品失败")); }, [source]); async function approve(p: Product) { try { await service.approveDerived(pid(p)); setDerived((rows) => rows.filter((x) => pid(x) !== pid(p))); notice("已通过审核"); } catch (e) { notice(e instanceof Error ? e.message : "审核失败"); } } async function reject(p: Product) { try { await service.rejectDerived(pid(p), [], "教师审核拒绝"); setDerived((rows) => rows.filter((x) => pid(x) !== pid(p))); notice("已拒绝"); } catch (e) { notice(e instanceof Error ? e.message : "拒绝失败"); } } return <section className="teacher-workspace"><div className="teacher-sources"><h2>教师看板</h2><p>选择原商品查看衍生品</p><div className="source-grid">{sources.map((p) => <button className={source && pid(source) === pid(p) ? "source-card active" : "source-card"} key={String(pid(p))} onClick={() => setSource(p)}>{picture(p) ? <img src={picture(p)} /> : <span className="image-empty">暂无图片</span>}<b>{title(p)}</b><small>{p.derived_count ?? 0} 个衍生品</small></button>)}</div></div><div className="review-list"><h2>衍生品审核</h2>{derived.map((p) => <article className="review-card" key={String(pid(p))}><div className="review-head">{picture(p) ? <img src={picture(p)} /> : <div className="image-empty">暂无图片</div>}<div><h3>{title(p)}</h3><span>{money(p)}</span></div><div className="review-actions"><button className="success" onClick={() => approve(p)}>通过</button><button className="danger" onClick={() => reject(p)}>拒绝</button></div></div></article>)}{!derived.length && <div className="empty-state">暂无待审核衍生品</div>}</div></section>; }

function Admin({ notice }: { notice: (s: string) => void }) { const [tab, setTab] = useState("users"); const [rows, setRows] = useState<unknown[]>([]); useEffect(() => { const task = tab === "users" ? service.getUsers() : tab === "models" ? service.getModelConfigs() : tab === "third" ? service.getThirdPartyConfigs() : tab === "settings" ? service.getSystemSettings() : service.getAppReleases(); task.then((data) => setRows(Array.isArray(data) ? data : Object.entries(data).map(([key, value]) => ({ key, value })))).catch((e) => notice(e instanceof Error ? e.message : "读取系统管理失败")); }, [tab]); const tabs = [{ id: "users", label: "用户管理" }, { id: "models", label: "模型配置" }, { id: "third", label: "第三方 API" }, { id: "settings", label: "业务配置" }, { id: "releases", label: "版本更新" }]; return <section className="admin-page"><div className="admin-tabs">{tabs.map((x) => <button className={tab === x.id ? "active" : ""} key={x.id} onClick={() => setTab(x.id)}>{x.label}</button>)}</div><div className="admin-table"><table><thead><tr><th>名称</th><th>类型</th><th>状态</th><th>信息</th></tr></thead><tbody>{rows.map((row, i) => { const x = row as Record<string, unknown>; return <tr key={i}><td>{String(x.real_name || x.username || x.config_name || x.key || x.version || "-")}</td><td>{String(x.role || x.model_type || x.service_type || "-")}</td><td>{x.status === 1 || x.status === true ? "启用" : "-"}</td><td>{String(x.model_name || x.provider || x.filename || x.value || x.release_notes || "-")}</td></tr>; })}</tbody></table>{!rows.length && <div className="empty-state">暂无数据</div>}</div></section>; }

function Studio({ search }: { search: (message: string, count: number) => Promise<void> }) { const [message, setMessage] = useState(""); const [count, setCount] = useState(10); const [busy, setBusy] = useState(false); return <section className="studio"><div className="studio-intro"><div><em>✦</em><h2>告诉我您想找什么样的产品？</h2><p>例如：最近在日本 TikTok 上热卖的厨房小工具，价格在1000日元以内</p></div><span>AI 选品助手</span></div><div className="prompt-box"><textarea placeholder="告诉我您想找什么样的产品？" value={message} onChange={(e) => setMessage(e.target.value)} /><div className="prompt-bottom"><small>{message.length}/300</small><select value={count} onChange={(e) => setCount(Number(e.target.value))}><option value={10}>10 条 · 10 积分</option><option value={15}>15 条 · 15 积分</option><option value={20}>20 条 · 20 积分</option></select><button className="primary" disabled={!message.trim() || busy} onClick={async () => { setBusy(true); try { await search(message, count); } finally { setBusy(false); } }}>{busy ? "分析中..." : "智能选品"}</button></div></div></section>; }

function Dashboard() { const [data, setData] = useState<Record<string, unknown> | null>(null); useEffect(() => { service.getPipelineStatus().then((x) => setData(x || {})).catch(() => setData({})); }, []); return <section className="dashboard-page"><div className="metric-grid"><div><span>任务状态</span><b>{String(data?.status || "运行中")}</b></div><div><span>今日任务</span><b>{String(data?.today_tasks || data?.task_count || 0)}</b></div><div><span>衍生品数量</span><b>{String(data?.derived_count || 0)}</b></div><div><span>接口状态</span><b className="ok">在线</b></div></div><div className="dashboard-panel"><h2>业务环节分布</h2><div className="bar-row"><span>FastMoss 同步</span><i style={{ width: "82%" }} /></div><div className="bar-row"><span>AI 衍生品</span><i style={{ width: "64%" }} /></div><div className="bar-row"><span>1688 匹配</span><i style={{ width: "48%" }} /></div><div className="dashboard-note">统计数据来自当前后端任务状态接口。</div></div></section>; }

function Store({ notice }: { notice: (s: string) => void }) { const [latest, setLatest] = useState<unknown>(null); const [history, setHistory] = useState<unknown[]>([]); useEffect(() => { Promise.all([service.getPublishLatest(), service.getPublishHistory()]).then(([a, b]) => { setLatest(a); setHistory(Array.isArray(b) ? b : []); }).catch((e) => notice(e instanceof Error ? e.message : "读取店铺任务失败")); }, []); return <section className="module-page"><div className="module-card"><h2>店铺管理</h2><p>配置店铺后，可读取已匹配的 1688 商品执行上架。</p><div className="module-actions"><button className="primary" onClick={() => notice("请先在店铺管理中配置店铺信息")}>配置店铺</button><button onClick={() => notice("已刷新上架任务")}>刷新任务</button></div><h3>最近任务</h3><pre>{JSON.stringify(latest || {}, null, 2)}</pre></div><div className="module-card"><h3>历史任务</h3><div className="simple-list">{history.map((row, i) => <div key={i}>{JSON.stringify(row)}</div>)}{!history.length && <span>暂无历史任务</span>}</div></div></section>; }

function Video({ notice }: { notice: (s: string) => void }) { const [projects, setProjects] = useState<VideoProject[]>([]); const [name, setName] = useState(""); const [busy, setBusy] = useState(false); const refresh = () => service.getVideoProjects().then(setProjects).catch((e) => notice(e instanceof Error ? e.message : "读取视频项目失败")); useEffect(() => { refresh(); }, []); async function create() { setBusy(true); try { await service.createVideoProject({ title: name || "新视频项目", target_market: "JP", video_language: "ja-JP" }); setName(""); refresh(); notice("视频项目已创建"); } catch (e) { notice(e instanceof Error ? e.message : "创建失败"); } finally { setBusy(false); } } return <section className="module-page"><div className="module-card"><h2>视频生成</h2><p>上传产品图，生成脚本，再提交视频。产品图会作为强参考。</p><div className="inline-form"><input placeholder="项目名称" value={name} onChange={(e) => setName(e.target.value)} /><button className="primary" disabled={busy} onClick={create}>创建项目</button></div></div><div className="module-card"><h3>视频项目</h3>{projects.map((p) => <div className="project-row" key={p.id}><div><b>{p.title || `项目 ${p.id}`}</b><span>{p.status || "draft"}</span></div><button onClick={async () => { try { await service.generateVideoScript(p.id); notice("脚本生成任务已提交"); refresh(); } catch (e) { notice(e instanceof Error ? e.message : "脚本生成失败"); } }}>生成脚本</button><button onClick={async () => { try { await service.submitVideoTask(p.id, {}); notice("视频生成任务已提交"); } catch (e) { notice(e instanceof Error ? e.message : "提交失败"); } }}>提交生成</button></div>)}{!projects.length && <div className="empty-state">暂无视频项目</div>}</div></section>; }

export default function App2() { const stored = localStorage.getItem("tk_electron_user"); const [user, setUser] = useState<User | null>(() => stored ? JSON.parse(stored) : null); const [page, setPage] = useState<Page>("studio"); const [rows, setRows] = useState<Product[]>([]); const [selected, setSelected] = useState<Product | null>(null); const [notice, setNotice] = useState(""); const allowed = useMemo(() => menus.filter((m) => m.roles.includes(user?.role || "student")), [user]); const flash = (s: string) => { setNotice(s); window.setTimeout(() => setNotice(""), 3000); }; async function load(next: Page) { if (!["library", "rank", "favorites"].includes(next)) return; try { const data = next === "library" ? await service.getLibrary() : next === "favorites" ? await service.getFavorites() : await service.getRanks({ region: "JP", list_type: "new", page: 1, pagesize: 50, paged: true }); const list = Array.isArray(data) ? data : (data as { items?: Product[] })?.items || []; setRows(list); setSelected(list[0] || null); } catch (e) { flash(e instanceof Error ? e.message : "读取数据失败"); } } useEffect(() => { if (user) load(page); }, [user, page]); if (!user) return <Login done={setUser} />; const collect = async (p: Product) => { try { await service.collect(p); flash("已加入采集箱"); } catch (e) { flash(e instanceof Error ? e.message : "加入失败"); } }; return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">TK</div><div><b>益行跨境 AI 平台</b><span>TikTok 日本选品专家</span></div></div><nav>{allowed.map((m) => <button key={m.id} className={page === m.id ? "active" : ""} onClick={() => setPage(m.id)}><i>{m.icon}</i>{m.label}</button>)}</nav><div className="account"><div className="avatar">{(user.real_name || user.username || "系").slice(0, 1)}</div><div className="account-copy"><b>{user.real_name || user.username}</b><span>{user.role} · 积分 {user.credits ?? 0}</span></div><button className="logout" onClick={() => { service.logout(); setUser(null); }}>退出登录</button></div></aside><main className="main"><header><div><h1>{menus.find((m) => m.id === page)?.label}</h1><span>益行跨境 · 日本市场选品工作台</span></div></header>{page === "studio" && <Studio search={async (message, count) => { await service.searchSelection(message, count); flash("选品完成，结果已进入选品库"); setPage("library"); }} />}{["library", "rank", "favorites"].includes(page) && <Products page={page} rows={rows} selected={selected} onSelect={setSelected} onCollect={collect} />}{page === "dashboard" && <Dashboard />}{page === "store" && <Store notice={flash} />}{page === "video" && <Video notice={flash} />}{page === "profile" && <div className="module-card"><h2>个人中心</h2><p>当前账号：{user.username || user.real_name}</p><p>当前积分：{user.credits ?? 0}</p></div>}{page === "teacher" && <Teacher notice={flash} />}{page === "admin" && <Admin notice={flash} />}{notice && <div className="toast">{notice}</div>}</main></div>; }
