import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import type { Product, Role, User } from "./types";
import * as service from "./api";
import "./styles.css";
import "./admin.css";
import "./teacher.css";
import App2 from "./app2";

type Page = "studio" | "library" | "rank" | "favorites" | "teacher" | "dashboard" | "profile" | "store" | "video" | "admin";
type Attribute = { id: number; name?: string; label?: string; enabled?: boolean };
const nav: Array<{ id: Page; label: string; icon: string; roles: Role[] }> = [
  { id: "studio", label: "智能选品", icon: "⌂", roles: ["admin", "teacher", "student"] },
  { id: "library", label: "选品库", icon: "▣", roles: ["admin", "student"] },
  { id: "rank", label: "新品榜单", icon: "♜", roles: ["admin", "teacher", "student"] },
  { id: "favorites", label: "采集箱", icon: "☆", roles: ["admin", "student"] },
  { id: "teacher", label: "教师看板", icon: "▤", roles: ["admin", "teacher"] },
  { id: "dashboard", label: "数据看板", icon: "◔", roles: ["admin", "teacher"] },
  { id: "store", label: "店铺管理", icon: "▥", roles: ["admin", "teacher", "student"] },
  { id: "video", label: "视频生成", icon: "▶", roles: ["admin", "teacher", "student"] },
  { id: "profile", label: "个人中心", icon: "⚙", roles: ["admin", "teacher", "student"] },
  { id: "admin", label: "系统管理", icon: "▦", roles: ["admin"] },
];
const dimensionNames = ["使用场景", "商品周期性", "目标群体", "短视频流量种草适配能力", "日本市场偏好", "是否属于新奇特商品", "复购属性", "竞品属性"];
function text(item: Product) { return item.title || item.derived_title || "未命名商品"; }
function img(item: Product) { return item.image_url || item.supplier_image_url || ""; }
function price(item: Product) { const value = Number(item.price ?? item.supplier_price ?? 0); const symbol = item.currency === "CNY" || item.region === "CN" ? "¥" : item.region === "JP" ? "円" : "$"; return `${symbol}${value.toFixed(2)}`; }
function count(item: Product) { return Number(item.sales_count ?? item.supplier_sales_count ?? 0).toLocaleString(); }
function idOf(item: Product) { return item.id ?? item.source_product_id ?? text(item); }
function reportValue(item: Product, name: string) { const report = typeof item.analysis_report === "string" ? item.analysis_report : JSON.stringify(item.analysis_report || ""); return report.includes(name) ? "已分析" : "待分析"; }

function Login({ onSuccess }: { onSuccess: (user: User) => void }) {
  const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  return <div className="login-page"><div className="login-visual"><div className="brand-mark large">TK</div><h1>益行跨境 AI 平台</h1><p>TikTok 日本市场智能选品工作台</p></div><form className="login-card" onSubmit={async (event) => { event.preventDefault(); setBusy(true); setError(""); try { onSuccess(await service.login(username, password)); } catch (e) { setError(e instanceof Error ? e.message : "登录失败"); } finally { setBusy(false); } }}><h2>欢迎回来</h2><p>使用账号登录工作台</p><label>账号<input value={username} onChange={(e) => setUsername(e.target.value)} required /></label><label>密码<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} required /></label>{error && <div className="error">{error}</div>}<button className="primary" disabled={busy}>{busy ? "登录中..." : "登录"}</button></form></div>;
}

function Studio({ onSearch }: { onSearch: (message: string, amount: number) => Promise<void> }) {
  const [message, setMessage] = useState(""); const [amount, setAmount] = useState(10); const [busy, setBusy] = useState(false);
  return <section className="studio"><div className="studio-intro"><div><em>✦</em><h2>告诉我您想找什么样的产品？</h2><p>例如：最近在日本 TikTok 上热卖的厨房小工具，价格在1000日元以内</p></div><span>AI 选品助手</span></div><div className="prompt-box"><textarea placeholder="告诉我您想找什么样的产品？" value={message} onChange={(e) => setMessage(e.target.value)} maxLength={300} /><div className="prompt-bottom"><small>{message.length}/300</small><select value={amount} onChange={(e) => setAmount(Number(e.target.value))}><option value={10}>10 条 · 10 积分</option><option value={15}>15 条 · 15 积分</option><option value={20}>20 条 · 20 积分</option></select><button className="primary" disabled={busy || !message.trim()} onClick={async () => { setBusy(true); try { await onSearch(message.trim(), amount); } finally { setBusy(false); } }}>{busy ? "分析中..." : "智能选品"}</button></div></div></section>;
}

function Report({ item, onCollect }: { item: Product | null; onCollect: (item: Product) => void }) {
  return <aside className="report"><h2>选品分析报告</h2>{item ? <><div className="report-product">{img(item) ? <img src={img(item)} /> : <div className="image-empty">暂无图片</div>}<div><h3>{text(item)}</h3><strong>{price(item)}</strong><p>销量 {count(item)}</p></div></div><div className="dimensions">{dimensionNames.map((name, index) => <div key={name}><i>{index + 1}</i><span><b>{name}</b><small>{reportValue(item, name)}</small></span><strong>{reportValue(item, name) === "已分析" ? "✓" : "-"}</strong></div>)}</div><button className="primary full" onClick={() => onCollect(item)}>加入采集箱</button></> : <div className="empty-state">选择商品查看报告</div>}</aside>;
}

function ProductWorkspace({ page, items, selected, onSelect, onCollect, onRemove }: { page: Page; items: Product[]; selected: Product | null; onSelect: (item: Product) => void; onCollect: (item: Product) => void; onRemove: (item: Product) => void }) {
  const heading = page === "library" ? "选品库" : page === "rank" ? "新品榜单" : page === "favorites" ? "采集箱" : "教师看板";
  return <div className="workspace"><section className="products"><div className="section-heading"><div><h2>{heading}</h2><p>{items.length} 个商品</p></div></div><div className="product-grid">{items.map((item) => <article key={String(idOf(item))} className={selected && idOf(selected) === idOf(item) ? "product selected" : "product"} onClick={() => onSelect(item)}><div className="image-wrap">{img(item) ? <img src={img(item)} loading="lazy" /> : <div className="image-empty">暂无图片</div>}</div><h3>{text(item)}</h3><div className="product-tag">{item.source_type || item.category || "商品"}</div><div className="product-meta"><strong>{price(item)}</strong><span>销量 {count(item)}</span></div><div className="product-actions">{page === "favorites" ? <button onClick={(e) => { e.stopPropagation(); onRemove(item); }}>移除</button> : <button onClick={(e) => { e.stopPropagation(); onCollect(item); }}>加入采集箱</button>}</div></article>)}</div>{!items.length && <div className="empty-state">暂无数据</div>}</section><Report item={selected} onCollect={onCollect} /></div>;
}

function TeacherReview({ products, onNotice }: { products: Product[]; onNotice: (message: string) => void }) {
  const [source, setSource] = useState<Product | null>(products[0] || null); const [derived, setDerived] = useState<Product[]>([]); const [attrs, setAttrs] = useState<Attribute[]>([]); const [loading, setLoading] = useState(false); const [rejecting, setRejecting] = useState<Product | null>(null); const [chosen, setChosen] = useState<number[]>([]); const [comment, setComment] = useState("");
  async function load(product: Product | null) { if (!product || idOf(product) === undefined) return; setLoading(true); try { const [items, dimensions] = await Promise.all([service.getTeacherDerived(idOf(product)), service.getSelectionAttributes()]); setDerived(items); setAttrs(dimensions); } catch (e) { onNotice(e instanceof Error ? e.message : "读取审核数据失败"); } finally { setLoading(false); } }
  useEffect(() => { load(source); }, [source]);
  async function approve(item: Product) { try { await service.approveDerived(idOf(item)); setDerived((list) => list.filter((row) => idOf(row) !== idOf(item))); onNotice("已通过审核"); } catch (e) { onNotice(e instanceof Error ? e.message : "审核失败"); } }
  async function reject() { if (!rejecting) return; try { await service.rejectDerived(idOf(rejecting), chosen, comment); setDerived((list) => list.filter((row) => idOf(row) !== idOf(rejecting))); setRejecting(null); setChosen([]); setComment(""); onNotice("已拒绝并更新属性权重"); } catch (e) { onNotice(e instanceof Error ? e.message : "拒绝失败"); } }
  const fallbackAttrs: Attribute[] = dimensionNames.map((name, index) => ({ id: index + 1, name }));
  const availableAttrs: Attribute[] = attrs.length ? attrs : fallbackAttrs;
  return <div className="teacher-workspace"><div className="teacher-sources"><h2>教师看板</h2><p>选择原商品查看对应的衍生品审核任务</p><div className="source-grid">{products.map((item) => <button key={String(idOf(item))} className={source && idOf(source) === idOf(item) ? "source-card active" : "source-card"} onClick={() => setSource(item)}>{img(item) ? <img src={img(item)} /> : <span className="image-empty">暂无图片</span>}<b>{text(item)}</b><small>{item.derived_count ?? 0} 个衍生品</small></button>)}</div></div><section className="review-list"><div className="section-heading"><div><h2>衍生品审核</h2><p>{source ? text(source) : "请选择原商品"}</p></div>{loading && <span>加载中...</span>}</div>{derived.map((item) => <article className="review-card" key={String(idOf(item))}><div className="review-head">{img(item) ? <img src={img(item)} /> : <div className="image-empty">暂无图片</div>}<div><h3>{text(item)}</h3><span>{price(item)} · 销量 {count(item)}</span></div><div className="review-actions"><button className="success" onClick={() => approve(item)}>通过</button><button className="danger" onClick={() => { setRejecting(item); setChosen([]); }}>拒绝</button></div></div><div className="review-dimensions">{dimensionNames.map((name) => <div key={name}><b>{name}</b><span>{reportValue(item, name)}</span></div>)}</div></article>)}{!derived.length && !loading && <div className="empty-state">当前原商品暂无待审核衍生品</div>}</section>{rejecting && <div className="modal-backdrop"><div className="modal"><h2>拒绝衍生品</h2><p>请选择需要降低权重的属性，可多选。</p><div className="attribute-picks">{availableAttrs.map((attr) => { const label = attr.name || attr.label || `属性 ${attr.id}`; return <label key={attr.id}><input type="checkbox" checked={chosen.includes(attr.id)} onChange={() => setChosen((list) => list.includes(attr.id) ? list.filter((id) => id !== attr.id) : [...list, attr.id])} />{label}</label>; })}</div><textarea placeholder="拒绝说明（可选）" value={comment} onChange={(e) => setComment(e.target.value)} /><div className="modal-actions"><button onClick={() => setRejecting(null)}>取消</button><button className="danger" onClick={reject}>确认拒绝</button></div></div></div>}</div>;
}

function Profile({ user, onNotice }: { user: User; onNotice: (message: string) => void }) { const [oldPassword, setOld] = useState(""); const [newPassword, setNew] = useState(""); return <section className="profile"><div className="profile-card"><div className="avatar large-avatar">{(user.real_name || user.username || "系").slice(0, 1)}</div><div><h2>{user.real_name || user.username}</h2><p>{user.role} · 当前积分 {user.credits ?? 0}</p></div></div><div className="settings-card"><h2>修改密码</h2><label>原密码<input type="password" value={oldPassword} onChange={(e) => setOld(e.target.value)} /></label><label>新密码<input type="password" value={newPassword} onChange={(e) => setNew(e.target.value)} /></label><button className="primary" onClick={async () => { try { await service.changePassword(oldPassword, newPassword); onNotice("密码已更新"); } catch (e) { onNotice(e instanceof Error ? e.message : "修改失败"); } }}>保存新密码</button></div></section>; }

function AdminPage({ onNotice }: { onNotice: (message: string) => void }) { const [tab, setTab] = useState("users"); const [rows, setRows] = useState<unknown[]>([]); const tabs = [{ id: "users", label: "用户管理" }, { id: "models", label: "模型配置" }, { id: "third", label: "第三方 API" }, { id: "settings", label: "业务配置" }, { id: "releases", label: "版本更新" }]; useEffect(() => { const task = tab === "users" ? service.getUsers() : tab === "models" ? service.getModelConfigs() : tab === "third" ? service.getThirdPartyConfigs() : tab === "settings" ? service.getSystemSettings() : service.getAppReleases(); task.then((data) => setRows(Array.isArray(data) ? data : Object.entries(data).map(([key, value]) => ({ key, value })))).catch((e) => onNotice(e instanceof Error ? e.message : "读取管理数据失败")); }, [tab]); return <section className="admin-page"><div className="admin-tabs">{tabs.map((item) => <button key={item.id} className={tab === item.id ? "active" : ""} onClick={() => setTab(item.id)}>{item.label}</button>)}</div><div className="admin-table">{rows.length ? <table><thead><tr><th>名称</th><th>类型</th><th>状态</th><th>信息</th></tr></thead><tbody>{rows.map((row, index) => { const item = row as Record<string, unknown>; return <tr key={index}><td>{String(item.real_name || item.username || item.config_name || item.key || item.version || "-")}</td><td>{String(item.role || item.model_type || item.service_type || "-")}</td><td>{item.status === 1 || item.status === true ? "启用" : item.status === 0 || item.status === false ? "停用" : "-"}</td><td>{String(item.model_name || item.provider || item.filename || item.value || item.release_notes || "-")}</td></tr>; })}</tbody></table> : <div className="empty-state">暂无数据</div>}</div></section>; }

function App() {
  const stored = localStorage.getItem("tk_electron_user"); const [user, setUser] = useState<User | null>(() => stored ? JSON.parse(stored) : null); const [page, setPage] = useState<Page>("studio"); const [items, setItems] = useState<Product[]>([]); const [selected, setSelected] = useState<Product | null>(null); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(false); const allowed = useMemo(() => nav.filter((item) => item.roles.includes(user?.role || "student")), [user]);
  function flash(message: string) { setNotice(message); window.setTimeout(() => setNotice(""), 3000); }
  async function loadPage(next: Page) { if (["admin", "dashboard", "profile", "store", "video"].includes(next)) return; setLoading(true); try { const data = next === "studio" ? await service.getRecommendations() : next === "library" ? await service.getLibrary() : next === "favorites" ? await service.getFavorites() : next === "teacher" ? await service.getTeacherProducts() : await service.getRanks({ region: "JP", list_type: "new", category: "全部", page: 1, pagesize: 50, paged: true }); const list = Array.isArray(data) ? data : (data as { items?: Product[] })?.items || []; setItems(list); setSelected((current) => current && list.some((row) => idOf(row) === idOf(current)) ? current : list[0] || null); } catch (e) { flash(e instanceof Error ? e.message : "读取数据失败"); } finally { setLoading(false); } }
  useEffect(() => { if (user) loadPage(page); }, [user, page]);
  if (!user) return <Login onSuccess={setUser} />;
  const collect = async (item: Product) => { try { await service.collect(item); flash("已加入采集箱"); } catch (e) { flash(e instanceof Error ? e.message : "加入失败"); } };
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">TK</div><div><b>益行跨境 AI 平台</b><span>TikTok 日本选品专家</span></div></div><nav>{allowed.map((item) => <button key={item.id} className={page === item.id ? "active" : ""} onClick={() => { setPage(item.id); setSelected(null); }}><i>{item.icon}</i>{item.label}</button>)}</nav><div className="account"><div className="avatar">{(user.real_name || user.username || "系").slice(0, 1)}</div><div className="account-copy"><b>{user.real_name || user.username}</b><span>{user.role} · 积分 {user.credits ?? 0}</span></div><button className="logout" onClick={() => { service.logout(); setUser(null); }}>退出登录</button></div></aside><main className="main"><header><div><h1>{nav.find((item) => item.id === page)?.label}</h1><span>益行跨境 · 日本市场选品工作台</span></div></header>{page === "studio" && <Studio onSearch={async (message, amount) => { setLoading(true); try { await service.searchSelection(message, amount); flash("选品完成，结果已进入选品库"); setPage("library"); } catch (e) { flash(e instanceof Error ? e.message : "选品失败"); } finally { setLoading(false); } }} />}{page === "profile" && <Profile user={user} onNotice={flash} />}{page === "teacher" && <TeacherReview products={items} onNotice={flash} />}{["library", "rank", "favorites"].includes(page) && <ProductWorkspace page={page} items={items} selected={selected} onSelect={setSelected} onCollect={collect} onRemove={async (item) => { if (item.id) { await service.removeFavorite(item.id); loadPage(page); } }} />}{page === "dashboard" && <div className="empty-state">数据看板模块正在迁移中，后端接口已保留。</div>}{page === "store" && <div className="empty-state">店铺管理模块正在迁移中，自动上架接口已保留。</div>}{page === "video" && <div className="empty-state">视频生成模块正在迁移中，视频项目接口已保留。</div>}{page === "admin" && <AdminPage onNotice={flash} />}{loading && <div className="loading-bar" />}{notice && <div className="toast">{notice}</div>}</main></div>;
}

createRoot(document.getElementById("root")!).render(<App2 />);
