const API = localStorage.getItem("tk_api_base") || "http://120.26.207.89:8000";
const state = { token: localStorage.getItem("tk_web_token") || "", user: JSON.parse(localStorage.getItem("tk_web_user") || "null"), page: "studio", selected: null, report: null, data: {} };

const navItems = [
  ["studio", "⌂", "智能选品"], ["library", "▣", "选品库"], ["rank", "♜", "新品榜单"], ["favorites", "☆", "采集箱"],
  ["teacher", "◈", "教师看板"], ["store", "▤", "店铺管理"], ["dashboard", "◒", "数据看板"], ["profile", "⚙", "个人中心"]
];

function esc(value) { return String(value ?? "").replace(/[&<>"']/g, s => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[s])); }
function img(value) { return value || "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='400' height='300'%3E%3Crect width='100%25' height='100%25' fill='%23eef2f5'/%3E%3Cpath d='M150 180l45-50 40 35 30-28 65 70H70z' fill='%23c7d7d5'/%3E%3C/svg%3E"; }
function money(item) { const currency = String(item?.currency || "").toUpperCase(); const c = ["CNY", "RMB"].includes(currency) ? "¥" : (item?.currency || (item?.region === "JP" ? "円" : "¥")); return `${c}${Number(item?.price || 0).toFixed(2)}`; }
function toast(message) { const el = document.querySelector("#toast"); el.textContent = message; el.classList.add("show"); setTimeout(() => el.classList.remove("show"), 2600); }
function role() { return state.user?.role || "student"; }
async function api(path, options = {}) {
  const headers = { "Content-Type": "application/json", ...(options.headers || {}) };
  if (state.token) headers.Authorization = `Bearer ${state.token}`;
  const res = await fetch(`${API}${path}`, { ...options, headers });
  const text = await res.text(); let body = null; try { body = text ? JSON.parse(text) : null; } catch { body = text; }
  if (!res.ok) { if (res.status === 401) { state.token = ""; state.user = null; persist(); render(); } throw new Error(body?.detail?.message || body?.detail || body?.message || `HTTP ${res.status}`); }
  return body;
}
function persist() { localStorage.setItem("tk_web_token", state.token); localStorage.setItem("tk_web_user", JSON.stringify(state.user)); }
function canSee(item) { const r = role(); if (r === "admin") return true; if (r === "teacher") return ["studio","rank","teacher","dashboard","profile"].includes(item); return ["studio","library","rank","favorites","store","profile"].includes(item); }

function layout(content) {
  const available = navItems.filter(([id]) => canSee(id));
  return `<div class="shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">TK</div><div><strong>益行跨境 AI 平台</strong><span>TikTok 日本选品专家</span></div></div><nav class="nav">${available.map(([id, icon, label]) => `<button class="${state.page === id ? "active" : ""}" data-page="${id}"><span class="nav-icon">${icon}</span><span>${label}</span></button>`).join("")}${role() === "admin" ? `<div class="nav-section">管理</div><button class="${state.page === "admin" ? "active" : ""}" data-page="admin"><span class="nav-icon">⚙</span><span>系统配置</span></button>` : ""}</nav><div class="account"><div class="account-name">${esc(state.user?.real_name || state.user?.username || "未登录")}</div><div class="account-role">${state.user ? ({admin:"系统管理员",teacher:"选品老师",student:"学生账号"}[role()] || role()) : "访客"}</div><div class="account-credit">积分 ${state.user?.credits ?? "-"}</div><button data-action="login">${state.user ? "退出登录" : "登录账号"}</button></div></aside><main class="main"><header class="topbar"><div class="crumb"><strong>${navItems.find(x => x[0] === state.page)?.[2] || "系统配置"}</strong> · 益行跨境 AI 平台</div><div class="top-actions"><span class="api-pill">${state.user ? "在线" : "未登录"} · 日本市场</span></div></header>${content}</main></div>`;
}

function productCard(item, actions = true) {
  const id = item.id || item.source_product_id; const derived = Number(item.derived_count || 0) > 0;
  return `<article class="product-card" data-product="${esc(id)}"><img class="product-img" src="${esc(img(item.image_url || item.supplier_image_url))}" alt="" loading="lazy"><div class="product-body"><div class="product-title">${esc(item.title || item.derived_title || "未命名商品")}</div><span class="tag">${esc(item.source_type === "ai_search" ? "AI搜索" : item.source_type === "derived" ? "衍生品" : item.region === "JP" ? "日本新品榜" : item.region || "商品")}</span><div class="product-meta"><span class="price">${money(item)}</span><span class="sales">销量 ${Number(item.sales_count || item.supplier_sales_count || 0).toLocaleString()}</span></div>${actions ? `<div class="card-actions"><button class="button secondary" data-action="report" data-id="${esc(id)}">查看报告</button><button class="button" data-action="collect" data-id="${esc(id)}">加入采集箱</button></div>` : ""}</div></article>`;
}

function reportPanel() {
  const item = state.selected || {}; const report = state.report || item.analysis_report || {};
  let data = report; if (typeof data === "string") { try { data = JSON.parse(data); } catch { data = {}; } }
  const dims = Object.entries(data || {}).filter(([key]) => key.toLowerCase().includes("dimension") || key.includes("维度")).slice(0, 8);
  const defaultDims = ["使用场景","商品周期性","目标群体","短视频流量种草适配能力","日本市场偏好","是否属于新奇特商品","复购属性","竞品属性"];
  return `<aside class="panel report"><div class="report-top"><img src="${esc(img(item.image_url || item.supplier_image_url))}" alt=""><div><h3>${esc(item.title || item.derived_title || "选择一个商品查看报告")}</h3><div class="report-price">${money(item)}</div><small class="sales">销量 ${Number(item.sales_count || item.supplier_sales_count || 0).toLocaleString()}</small></div></div><div class="report-tabs"><button class="active">选品分析报告</button><button>人群匹配</button><button>使用场景</button></div><div class="dimension-list">${(dims.length ? dims : defaultDims.map((x, i) => [x, "暂无分析内容"])).map(([key, value], i) => `<div class="dimension"><span class="dimension-icon">${i + 1}</span><div><strong>${esc(key.replace(/^dimension[_-]?\d+[:：]?/i, "") || key)}</strong><p>${esc(typeof value === "object" ? JSON.stringify(value) : value)}</p></div><span class="dimension-score">${typeof value === "string" && value.includes("分") ? esc(value.match(/[0-9.]+/)?.[0] || "-") : "-"}</span></div>`).join("")}</div><div class="report-actions"><button class="button secondary" data-action="collect" data-id="${esc(item.id || item.source_product_id || "")}">加入采集箱</button><button class="button" data-action="export">导出报告</button></div></aside>`;
}

async function studio() {
  const [recommendations, ranks] = await Promise.all([api("/api/derived-recommendations?limit=12"), api("/api/daily-recommendations?region=JP&list_type=new&category=全部")]);
  state.data.recommendations = recommendations || []; state.data.ranks = ranks || [];
  return `<div class="page-grid"><section class="content"><div class="hero"><div><h1>AI 智能选品</h1><p>用自然语言描述需求，快速发现适合 TikTok Japan 的商品机会。</p></div><button class="button secondary">使用教程</button></div><div class="panel prompt-panel"><div class="prompt-label"><i>✦</i> 告诉我您想找什么样的产品？</div><textarea id="prompt" class="prompt-input" maxlength="300" placeholder="例如：最近在日本TikTok上热卖的厨房小工具，价格在1000日元以内"></textarea><div class="prompt-footer"><span class="prompt-hint">搜索结果会保存到选品库，并自动补充货源信息</span><button class="button" data-action="search">智能选品</button></div><div id="search-progress" class="progress" hidden><i></i></div></div><div class="section"><div class="section-head"><h2>今日选品推荐</h2><small>每日随机推荐 12 个衍生品</small></div><div class="card-grid">${state.data.recommendations.map(x => productCard(x)).join("") || `<div class="empty">暂无衍生品推荐，请先完成商品衍生。</div>`}</div></div><div class="section"><div class="section-head"><h2>新品榜单</h2><small>日本地区 · FastMoss</small></div><div class="card-grid">${state.data.ranks.slice(0, 8).map(x => productCard(x)).join("") || `<div class="empty">暂无新品榜数据。</div>`}</div></div></section>${reportPanel()}</div>`;
}

async function library() { const items = await api("/api/ai/search-results"); state.data.library = items || []; if (!state.selected && state.data.library[0]) state.selected = state.data.library[0]; return `<div class="page-grid"><section class="content"><div class="hero"><div><h1>选品库</h1><p>管理你的 AI 搜索结果和已加入的选品。</p></div></div><div class="toolbar"><select><option>全部国家/地区</option><option>中国</option><option>日本</option><option>美国</option></select><select><option>全部商品分类</option><option>家居日用</option><option>美妆个护</option><option>宠物用品</option></select></div><div class="card-grid">${state.data.library.map(x => productCard(x)).join("") || `<div class="empty">暂无选品。请在智能选品中发起一次搜索。</div>`}</div></section>${reportPanel()}</div>`; }

async function rank() { const region = state.data.rankRegion || "JP", type = state.data.rankType || "new"; const data = await api(`/api/daily-recommendations?region=${region}&list_type=${type}&category=全部&paged=true&page=1&pagesize=50`); const items = data?.items || data || []; state.data.rankItems = items; const regions = [["ALL","全部"],["US","美国"],["JP","日本"],["TH","泰国"],["VN","越南"],["SG","新加坡"]]; const categories = ["全部","美妆个护","女装与女士内衣","家居日用","食品饮料","手机与数码","运动与户外","玩具和爱好"]; return `<section class="content"><div class="hero"><div><h1>新品榜单</h1><p>从多个市场快速定位正在增长的商品机会。</p></div><button class="button blue" data-action="refresh-rank">刷新榜单</button></div><div class="panel listing-filter"><div class="filter-row"><b>国家/地区</b>${regions.map(([code,label]) => `<button class="filter-chip ${region === code ? "selected" : ""}" data-region="${code}">${label}</button>`).join("")}</div><div class="filter-row"><b>商品分类</b>${categories.map(label => `<button class="filter-chip ${label === "全部" ? "selected" : ""}">${label}</button>`).join("")}<button class="filter-expand">展开筛选⌄</button></div><div class="filter-row"><b>商品榜单</b>${[["sales","销量榜"],["new","新品榜"],["hot","热销榜"]].map(([code,label]) => `<button class="filter-chip ${type === code ? "selected" : ""}" data-type="${code}">${label}</button>`).join("")}</div></div><div class="listing-summary"><strong>${type === "new" ? "新品榜" : type === "sales" ? "销量榜" : "热销榜"}</strong><span>${region === "JP" ? "日本" : region === "US" ? "美国" : region} · 共 ${data?.total ?? items.length} 个商品</span></div><div class="listing-table">${items.map((x, i) => `<article class="listing-row"><div class="rank-no">${String(i + 1).padStart(2, "0")}</div><img src="${esc(img(x.image_url))}" alt="" loading="lazy"><div class="listing-name"><strong>${esc(x.title || "未命名商品")}</strong><span>${esc(x.category || "未分类")} · ${esc(x.shop_name || "TikTok 商品")}</span></div><div class="listing-stat"><small>价格</small><b>${money(x)}</b></div><div class="listing-stat"><small>销量</small><b>${Number(x.sales_count || 0).toLocaleString()}</b></div><div class="listing-stat"><small>地区</small><b>${esc(x.region || region)}</b></div><button class="button secondary listing-action" data-action="report" data-id="${esc(x.id)}">查看详情</button></article>`).join("") || `<div class="empty">暂无榜单数据。</div>`}</div></section>`; }

async function favorites() { const items = await api("/api/favorites"); state.data.favorites = items || []; return `<section class="content"><div class="hero"><div><h1>采集箱</h1><p>保存需要进一步跟进的商品。</p></div></div><div class="table-wrap"><table><thead><tr><th>商品</th><th>来源</th><th>国家/地区</th><th>分类</th><th>价格</th><th>销量</th><th>操作</th></tr></thead><tbody>${state.data.favorites.map(x => `<tr><td><div class="table-product"><img src="${esc(img(x.image_url))}" alt=""><span>${esc(x.title)}</span></div></td><td>${esc(x.source_type || "商品")}</td><td>${esc(x.region || "-")}</td><td>${esc(x.category || "-")}</td><td class="price">${money(x)}</td><td>${Number(x.sales_count || 0).toLocaleString()}</td><td><button class="button secondary" data-action="delete-favorite" data-id="${x.id}">移除</button></td></tr>`).join("") || `<tr><td colspan="7"><div class="empty">采集箱还是空的。</div></td></tr>`}</tbody></table></div></section>`; }

async function teacher() { const items = await api("/api/teacher/products"); state.data.teacher = items || []; return `<section class="content"><div class="hero"><div><h1>教师看板</h1><p>查看日本新品榜商品，并审核所有用户生成的衍生品。</p></div></div><div class="card-grid">${state.data.teacher.map(x => productCard(x)).join("") || `<div class="empty">暂无教师审核商品。</div>`}</div></section>`; }

function profile() { return `<section class="content"><div class="hero"><div><h1>个人中心</h1><p>管理登录信息、密码和积分。</p></div></div><div class="stat-grid"><div class="stat"><span>当前用户</span><strong>${esc(state.user?.real_name || state.user?.username || "未登录")}</strong></div><div class="stat"><span>账户角色</span><strong>${esc(role())}</strong></div><div class="stat"><span>剩余积分</span><strong>${state.user?.credits ?? "-"}</strong></div></div><div class="panel panel-pad"><h2>修改密码</h2><div class="field"><label>旧密码</label><input id="old-password" type="password"></div><div class="field"><label>新密码</label><input id="new-password" type="password"></div><div class="card-actions"><button class="button" data-action="password">保存新密码</button></div></div></section>`; }

function admin() { return `<section class="content"><div class="hero"><div><h1>系统配置</h1><p>管理员配置模型、第三方 API、地区和业务阈值。</p></div></div><div class="stat-grid"><div class="stat"><span>配置模块</span><strong>4</strong></div><div class="stat"><span>后端状态</span><strong>在线</strong></div><div class="stat"><span>FastMoss</span><strong>可同步</strong></div></div><div class="panel panel-pad"><h2>第三方 API</h2><p class="prompt-hint">配置和同步按钮继续复用现有后端接口，Web 端不会修改服务端配置。</p><button class="button" data-action="sync-rank">同步新品榜单</button></div></section>`; }

async function renderPage() { let content; try { content = state.page === "studio" ? await studio() : state.page === "library" ? await library() : state.page === "rank" ? await rank() : state.page === "favorites" ? await favorites() : state.page === "teacher" ? await teacher() : state.page === "profile" ? profile() : state.page === "admin" ? admin() : `<div class="empty">该功能正在接入。</div>`; } catch (e) { content = `<div class="empty">加载失败：${esc(e.message)}<br><button class="button secondary" data-action="retry">重试</button></div>`; } document.querySelector("#app").innerHTML = layout(content); bind(); }

function showLogin() { document.body.insertAdjacentHTML("beforeend", `<div class="login-backdrop" id="login"><form class="login-card"><h2>登录益行跨境 AI 平台</h2><p>使用账号密码登录，后续可接入手机验证码登录。</p><div class="field"><label>账号</label><input name="username" required autocomplete="username"></div><div class="field"><label>密码</label><input name="password" type="password" required autocomplete="current-password"></div><div class="login-actions"><button class="button secondary" type="button" data-action="close-login">取消</button><button class="button" type="submit">登录</button></div></form></div>`); document.querySelector("#login form").onsubmit = async e => { e.preventDefault(); const data = Object.fromEntries(new FormData(e.target)); try { const result = await api("/api/auth/login", { method: "POST", body: JSON.stringify(data) }); state.token = result.access_token; state.user = result.user || result; persist(); document.querySelector("#login").remove(); render(); } catch (err) { toast(err.message); } }; }

async function action(e) { const el = e.target.closest("[data-action]"); if (!el) return; const action = el.dataset.action; try {
  if (action === "login") { if (state.user) { state.token = ""; state.user = null; persist(); render(); } else showLogin(); return; }
  if (action === "close-login") { document.querySelector("#login")?.remove(); return; }
  if (action === "retry") { render(); return; }
  if (action === "refresh-rank") { state.page = "rank"; render(); return; }
  if (!state.user) { showLogin(); return; }
  if (action === "search") { const message = document.querySelector("#prompt")?.value.trim(); if (!message) return toast("请先输入选品需求"); el.disabled = true; const bar = document.querySelector("#search-progress"); bar.hidden = false; bar.querySelector("i").style.width = "35%"; const result = await api("/api/ai/chat-selection", { method: "POST", body: JSON.stringify({ message, count: 10 }) }); bar.querySelector("i").style.width = "100%"; toast("选品完成，结果已写入选品库"); setTimeout(() => { state.page = "library"; render(); }, 650); return result; }
  if (action === "report") { const item = [...(state.data.library || []), ...(state.data.recommendations || []), ...(state.data.rankItems || []), ...(state.data.teacher || [])].find(x => String(x.id || x.source_product_id) === String(el.dataset.id)); if (item) { state.selected = item; state.report = item.analysis_report; render(); } return; }
  if (action === "collect") { const item = [...(state.data.library || []), ...(state.data.recommendations || []), ...(state.data.rankItems || []), ...(state.data.teacher || [])].find(x => String(x.id || x.source_product_id) === String(el.dataset.id)); if (!item) return; await api("/api/favorites", { method: "POST", body: JSON.stringify({ product: item }) }); toast("已加入采集箱"); return; }
  if (action === "delete-favorite") { await api(`/api/favorites/${el.dataset.id}`, { method: "DELETE" }); toast("已移除"); render(); return; }
  if (action === "password") { await api("/api/auth/change-password", { method: "POST", body: JSON.stringify({ old_password: document.querySelector("#old-password").value, new_password: document.querySelector("#new-password").value }) }); toast("密码已更新"); return; }
  if (action === "sync-rank") { await api("/api/fastmoss/sync-configured", { method: "POST" }); toast("新品榜单同步完成"); return; }
} catch (err) { toast(err.message); } }

function bind() { document.querySelectorAll("[data-page]").forEach(x => x.onclick = () => { state.page = x.dataset.page; state.selected = null; render(); }); document.querySelectorAll("[data-action]").forEach(x => x.onclick = action); document.querySelectorAll("[data-region]").forEach(x => x.onclick = () => { state.data.rankRegion = x.dataset.region; render(); }); document.querySelectorAll("[data-type]").forEach(x => x.onclick = () => { state.data.rankType = x.dataset.type; render(); }); document.querySelectorAll(".product-card").forEach(card => card.onclick = e => { if (e.target.closest("button")) return; const item = [...(state.data.library || []), ...(state.data.recommendations || []), ...(state.data.rankItems || []), ...(state.data.teacher || [])].find(x => String(x.id || x.source_product_id) === card.dataset.product); if (item) { state.selected = item; state.report = item.analysis_report; render(); } }); }
function render() { if (!state.user && state.page !== "studio") state.page = "studio"; renderPage(); }
render();
